services:
  api:
    build:
      context: ./../oi-docker/php82-apache
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 18.17.0
    ports:
      - '80:80'
    volumes:
      - './api:/var/www/html'
    depends_on:
      - mysql
  mysql:
    image: 'library/mariadb:latest'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - '~/volumes/catalog/mysql/:/var/lib/mysql'
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
